/*
-- Query: SELECT region, `name` as 'name', capital FROM java_backend.countries
LIMIT 0, 1000

-- Date: 2024-06-10 16:27
*/
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Afghanistan','Kabul');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Albania','Tirana');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Algeria','Algiers');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Angola','Luanda');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Argentina','Buenos Aires');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Armenia','Yerevan');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Oceania','Australia','Canberra');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Austria','Vienna');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Azerbaijan','Baku');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Bahrain','Manama');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Bangladesh','Dhaka');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Belarus','Minsk');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Belgium','Brussels');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Belize','Belmopan');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Benin','Porto-Novo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Bhutan','Thimphu');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Bolivia (Plurinational State of)','Sucre');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Bosnia and Herzegovina','Sarajevo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Botswana','Gaborone');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Brazil','Brasília');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Bulgaria','Sofia');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Burkina Faso','Ouagadougou');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Burundi','Gitega');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Cambodia','Phnom Penh');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Cameroon','Yaoundé');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Canada','Ottawa');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Cabo Verde','Praia');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Central African Republic','Bangui');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Chad','N\'Djamena');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Chile','Santiago');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','China','Beijing');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Colombia','Bogotá');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Comoros','Moroni');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Congo','Brazzaville');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Costa Rica','San José');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Croatia','Zagreb');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Cuba','Havana');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Cyprus','Nicosia');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Czech Republic','Prague');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Denmark','Copenhagen');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Djibouti','Djibouti');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Dominican Republic','Santo Domingo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Ecuador','Quito');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Egypt','Cairo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','El Salvador','San Salvador');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Equatorial Guinea','Malabo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Estonia','Tallinn');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Ethiopia','Addis Ababa');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Oceania','Fiji','Suva');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Finland','Helsinki');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','France','Paris');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Gabon','Libreville');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Georgia','Tbilisi');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Germany','Berlin');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Ghana','Accra');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Greece','Athens');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Guatemala','Guatemala City');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Guinea','Conakry');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Guinea-Bissau','Bissau');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Guyana','Georgetown');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Haiti','Port-au-Prince');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Vatican City','Vatican City');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Honduras','Tegucigalpa');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Hong Kong','City of Victoria');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Hungary','Budapest');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Iceland','Reykjavík');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','India','New Delhi');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Indonesia','Jakarta');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Côte d\'Ivoire','Yamoussoukro');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Iran (Islamic Republic of)','Tehran');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Iraq','Baghdad');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Ireland','Dublin');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Israel','Jerusalem');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Italy','Rome');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Jamaica','Kingston');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Japan','Tokyo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Jordan','Amman');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Kazakhstan','Nur-Sultan');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Kenya','Nairobi');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Kuwait','Kuwait City');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Kyrgyzstan','Bishkek');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Lao People\'s Democratic Republic','Vientiane');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Latvia','Riga');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Lebanon','Beirut');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Lesotho','Maseru');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Liberia','Monrovia');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Libya','Tripoli');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Lithuania','Vilnius');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Luxembourg','Luxembourg');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','North Macedonia','Skopje');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Madagascar','Antananarivo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Malawi','Lilongwe');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Malaysia','Kuala Lumpur');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Maldives','Malé');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Mali','Bamako');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Malta','Valletta');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Mauritania','Nouakchott');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Mauritius','Port Louis');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Mexico','Mexico City');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Moldova (Republic of)','Chișinău');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Mongolia','Ulan Bator');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Montenegro','Podgorica');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Morocco','Rabat');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Mozambique','Maputo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Myanmar','Naypyidaw');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Namibia','Windhoek');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Nepal','Kathmandu');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Netherlands','Amsterdam');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Oceania','New Zealand','Wellington');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Nicaragua','Managua');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Niger','Niamey');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Nigeria','Abuja');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Korea (Democratic People\'s Republic of)','Pyongyang');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Norway','Oslo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Oman','Muscat');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Pakistan','Islamabad');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Panama','Panama City');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Oceania','Papua New Guinea','Port Moresby');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Paraguay','Asunción');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Peru','Lima');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Philippines','Manila');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Poland','Warsaw');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Portugal','Lisbon');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Qatar','Doha');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Romania','Bucharest');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Russian Federation','Moscow');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Rwanda','Kigali');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Saint Lucia','Castries');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Sao Tome and Principe','São Tomé');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Saudi Arabia','Riyadh');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Senegal','Dakar');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Serbia','Belgrade');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Seychelles','Victoria');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Sierra Leone','Freetown');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Singapore','Singapore');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Slovakia','Bratislava');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Slovenia','Ljubljana');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Somalia','Mogadishu');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','South Africa','Pretoria');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Korea (Republic of)','Seoul');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','South Sudan','Juba');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Spain','Madrid');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Sri Lanka','Sri Jayawardenepura Kotte');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Sudan','Khartoum');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Suriname','Paramaribo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Eswatini','Mbabane');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Sweden','Stockholm');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Switzerland','Bern');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Syrian Arab Republic','Damascus');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Taiwan','Taipei');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Tajikistan','Dushanbe');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Tanzania, United Republic of','Dodoma');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Thailand','Bangkok');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Timor-Leste','Dili');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Togo','Lomé');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Trinidad and Tobago','Port of Spain');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Tunisia','Tunis');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Turkey','Ankara');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Turkmenistan','Ashgabat');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Uganda','Kampala');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Europe','Ukraine','Kyiv');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','United Arab Emirates','Abu Dhabi');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','United States of America','Washington, D.C.');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Uruguay','Montevideo');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Uzbekistan','Tashkent');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Americas','Venezuela (Bolivarian Republic of)','Caracas');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Vietnam','Hanoi');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Asia','Yemen','Sana\'a');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Zambia','Lusaka');
INSERT INTO `` (`region`,`name`,`capital`) VALUES ('Africa','Zimbabwe','Harare');
